// AUTO-GENERATED by scripts/export_ts_data.py — DO NOT EDIT BY HAND.
// Source of truth: database/seed/*.csv (regenerate with: python scripts/export_ts_data.py)

export interface VehicleRow {
  vehicleId: number; year: number; make: string; model: string; trim: string | null;
  vehicleClass: string; segment: string; luxuryFlag: boolean; powertrain: string;
  turboFlag: boolean; drivetrain: string;
}
export interface RiskScoreRow {
  vehicleId: number; brandRepairCost: number; modelReliability: number;
  powertrainComplexity: number; electronicsComplexity: number; knownFailurePoints: number;
  luxuryPartsCost: number; hybridEvComponents: number; claimsLikelihood: number;
  referenceTotal: number;
}
export interface CoverageTierRow { tierKey: string; name: string; exclusionaryFlag: boolean; }
export interface BandRow {
  bandKey: string; minValue: number; maxValue: number | null; riskScore: number; priceMult: number;
}
export interface ObservationRow {
  obsId: number; vehicleId: number | null; vehicleClass: string | null; coverageTier: string;
  termMonths: number | null; retailPrice: number | null; sourceType: string;
}

export const DATA_VERSION = "0.1.0";

export const DATA_GENERATED_AT = "2026-06-20";


export const VEHICLES: VehicleRow[] = [
  {
    "vehicleId": 1,
    "year": 2021,
    "make": "Toyota",
    "model": "Camry",
    "trim": "LE",
    "vehicleClass": "sedan_midsize",
    "segment": "mainstream",
    "luxuryFlag": false,
    "powertrain": "ice",
    "turboFlag": false,
    "drivetrain": "fwd"
  },
  {
    "vehicleId": 2,
    "year": 2021,
    "make": "Honda",
    "model": "Accord",
    "trim": "EX",
    "vehicleClass": "sedan_midsize",
    "segment": "mainstream",
    "luxuryFlag": false,
    "powertrain": "ice",
    "turboFlag": true,
    "drivetrain": "fwd"
  },
  {
    "vehicleId": 3,
    "year": 2021,
    "make": "Ford",
    "model": "F-150",
    "trim": "XLT",
    "vehicleClass": "truck_fullsize",
    "segment": "mainstream",
    "luxuryFlag": false,
    "powertrain": "ice",
    "turboFlag": true,
    "drivetrain": "4wd"
  },
  {
    "vehicleId": 4,
    "year": 2021,
    "make": "Chevrolet",
    "model": "Silverado 1500",
    "trim": "LT",
    "vehicleClass": "truck_fullsize",
    "segment": "mainstream",
    "luxuryFlag": false,
    "powertrain": "ice",
    "turboFlag": false,
    "drivetrain": "4wd"
  },
  {
    "vehicleId": 5,
    "year": 2021,
    "make": "Toyota",
    "model": "RAV4",
    "trim": "XLE",
    "vehicleClass": "suv_compact",
    "segment": "mainstream",
    "luxuryFlag": false,
    "powertrain": "ice",
    "turboFlag": false,
    "drivetrain": "awd"
  },
  {
    "vehicleId": 6,
    "year": 2021,
    "make": "Honda",
    "model": "CR-V",
    "trim": "EX",
    "vehicleClass": "suv_compact",
    "segment": "mainstream",
    "luxuryFlag": false,
    "powertrain": "ice",
    "turboFlag": true,
    "drivetrain": "awd"
  },
  {
    "vehicleId": 7,
    "year": 2021,
    "make": "Jeep",
    "model": "Grand Cherokee",
    "trim": "Limited",
    "vehicleClass": "suv_midsize",
    "segment": "mainstream",
    "luxuryFlag": false,
    "powertrain": "ice",
    "turboFlag": false,
    "drivetrain": "4wd"
  },
  {
    "vehicleId": 8,
    "year": 2021,
    "make": "Dodge",
    "model": "Charger",
    "trim": "R/T",
    "vehicleClass": "sedan_performance",
    "segment": "performance",
    "luxuryFlag": false,
    "powertrain": "ice",
    "turboFlag": false,
    "drivetrain": "rwd"
  },
  {
    "vehicleId": 9,
    "year": 2021,
    "make": "BMW",
    "model": "3 Series",
    "trim": "330i",
    "vehicleClass": "luxury_sedan",
    "segment": "luxury",
    "luxuryFlag": true,
    "powertrain": "ice",
    "turboFlag": true,
    "drivetrain": "rwd"
  },
  {
    "vehicleId": 10,
    "year": 2021,
    "make": "Mercedes-Benz",
    "model": "C-Class",
    "trim": "C 300",
    "vehicleClass": "luxury_sedan",
    "segment": "luxury",
    "luxuryFlag": true,
    "powertrain": "ice",
    "turboFlag": true,
    "drivetrain": "rwd"
  },
  {
    "vehicleId": 11,
    "year": 2021,
    "make": "Tesla",
    "model": "Model 3",
    "trim": "Long Range",
    "vehicleClass": "ev",
    "segment": "luxury",
    "luxuryFlag": true,
    "powertrain": "ev",
    "turboFlag": false,
    "drivetrain": "awd"
  },
  {
    "vehicleId": 12,
    "year": 2021,
    "make": "Hyundai",
    "model": "Elantra",
    "trim": "SEL",
    "vehicleClass": "sedan_economy",
    "segment": "economy",
    "luxuryFlag": false,
    "powertrain": "ice",
    "turboFlag": false,
    "drivetrain": "fwd"
  },
  {
    "vehicleId": 13,
    "year": 2021,
    "make": "Kia",
    "model": "Telluride",
    "trim": "EX",
    "vehicleClass": "suv_midsize",
    "segment": "mainstream",
    "luxuryFlag": false,
    "powertrain": "ice",
    "turboFlag": false,
    "drivetrain": "awd"
  },
  {
    "vehicleId": 14,
    "year": 2021,
    "make": "Nissan",
    "model": "Altima",
    "trim": "SV",
    "vehicleClass": "sedan_midsize",
    "segment": "mainstream",
    "luxuryFlag": false,
    "powertrain": "ice",
    "turboFlag": false,
    "drivetrain": "fwd"
  },
  {
    "vehicleId": 15,
    "year": 2021,
    "make": "Subaru",
    "model": "Outback",
    "trim": "Premium",
    "vehicleClass": "suv_compact",
    "segment": "mainstream",
    "luxuryFlag": false,
    "powertrain": "ice",
    "turboFlag": false,
    "drivetrain": "awd"
  }
];

export const RISK_SCORES: RiskScoreRow[] = [
  {
    "vehicleId": 1,
    "brandRepairCost": 20,
    "modelReliability": 15,
    "powertrainComplexity": 25,
    "electronicsComplexity": 30,
    "knownFailurePoints": 15,
    "luxuryPartsCost": 10,
    "hybridEvComponents": 0,
    "claimsLikelihood": 20,
    "referenceTotal": 18
  },
  {
    "vehicleId": 2,
    "brandRepairCost": 22,
    "modelReliability": 18,
    "powertrainComplexity": 30,
    "electronicsComplexity": 32,
    "knownFailurePoints": 20,
    "luxuryPartsCost": 12,
    "hybridEvComponents": 0,
    "claimsLikelihood": 22,
    "referenceTotal": 20
  },
  {
    "vehicleId": 3,
    "brandRepairCost": 45,
    "modelReliability": 45,
    "powertrainComplexity": 45,
    "electronicsComplexity": 45,
    "knownFailurePoints": 45,
    "luxuryPartsCost": 35,
    "hybridEvComponents": 10,
    "claimsLikelihood": 45,
    "referenceTotal": 38
  },
  {
    "vehicleId": 4,
    "brandRepairCost": 48,
    "modelReliability": 48,
    "powertrainComplexity": 45,
    "electronicsComplexity": 45,
    "knownFailurePoints": 48,
    "luxuryPartsCost": 35,
    "hybridEvComponents": 5,
    "claimsLikelihood": 48,
    "referenceTotal": 40
  },
  {
    "vehicleId": 5,
    "brandRepairCost": 22,
    "modelReliability": 18,
    "powertrainComplexity": 28,
    "electronicsComplexity": 35,
    "knownFailurePoints": 20,
    "luxuryPartsCost": 12,
    "hybridEvComponents": 10,
    "claimsLikelihood": 22,
    "referenceTotal": 21
  },
  {
    "vehicleId": 6,
    "brandRepairCost": 24,
    "modelReliability": 20,
    "powertrainComplexity": 35,
    "electronicsComplexity": 35,
    "knownFailurePoints": 28,
    "luxuryPartsCost": 14,
    "hybridEvComponents": 8,
    "claimsLikelihood": 25,
    "referenceTotal": 23
  },
  {
    "vehicleId": 7,
    "brandRepairCost": 65,
    "modelReliability": 85,
    "powertrainComplexity": 60,
    "electronicsComplexity": 70,
    "knownFailurePoints": 80,
    "luxuryPartsCost": 55,
    "hybridEvComponents": 15,
    "claimsLikelihood": 78,
    "referenceTotal": 60
  },
  {
    "vehicleId": 8,
    "brandRepairCost": 60,
    "modelReliability": 70,
    "powertrainComplexity": 65,
    "electronicsComplexity": 55,
    "knownFailurePoints": 60,
    "luxuryPartsCost": 50,
    "hybridEvComponents": 0,
    "claimsLikelihood": 65,
    "referenceTotal": 52
  },
  {
    "vehicleId": 9,
    "brandRepairCost": 85,
    "modelReliability": 55,
    "powertrainComplexity": 70,
    "electronicsComplexity": 80,
    "knownFailurePoints": 70,
    "luxuryPartsCost": 90,
    "hybridEvComponents": 5,
    "claimsLikelihood": 72,
    "referenceTotal": 62
  },
  {
    "vehicleId": 10,
    "brandRepairCost": 88,
    "modelReliability": 58,
    "powertrainComplexity": 72,
    "electronicsComplexity": 85,
    "knownFailurePoints": 72,
    "luxuryPartsCost": 92,
    "hybridEvComponents": 5,
    "claimsLikelihood": 75,
    "referenceTotal": 65
  },
  {
    "vehicleId": 11,
    "brandRepairCost": 70,
    "modelReliability": 45,
    "powertrainComplexity": 40,
    "electronicsComplexity": 95,
    "knownFailurePoints": 55,
    "luxuryPartsCost": 75,
    "hybridEvComponents": 90,
    "claimsLikelihood": 58,
    "referenceTotal": 57
  },
  {
    "vehicleId": 12,
    "brandRepairCost": 30,
    "modelReliability": 35,
    "powertrainComplexity": 35,
    "electronicsComplexity": 35,
    "knownFailurePoints": 40,
    "luxuryPartsCost": 15,
    "hybridEvComponents": 0,
    "claimsLikelihood": 35,
    "referenceTotal": 29
  },
  {
    "vehicleId": 13,
    "brandRepairCost": 35,
    "modelReliability": 30,
    "powertrainComplexity": 40,
    "electronicsComplexity": 45,
    "knownFailurePoints": 35,
    "luxuryPartsCost": 30,
    "hybridEvComponents": 0,
    "claimsLikelihood": 35,
    "referenceTotal": 31
  },
  {
    "vehicleId": 14,
    "brandRepairCost": 38,
    "modelReliability": 50,
    "powertrainComplexity": 45,
    "electronicsComplexity": 35,
    "knownFailurePoints": 55,
    "luxuryPartsCost": 18,
    "hybridEvComponents": 0,
    "claimsLikelihood": 48,
    "referenceTotal": 36
  },
  {
    "vehicleId": 15,
    "brandRepairCost": 40,
    "modelReliability": 30,
    "powertrainComplexity": 45,
    "electronicsComplexity": 40,
    "knownFailurePoints": 42,
    "luxuryPartsCost": 25,
    "hybridEvComponents": 0,
    "claimsLikelihood": 38,
    "referenceTotal": 32
  }
];

export const COVERAGE_TIERS: CoverageTierRow[] = [
  {
    "tierKey": "comprehensive",
    "name": "Comprehensive",
    "exclusionaryFlag": false
  },
  {
    "tierKey": "cpo",
    "name": "Certified Pre-Owned",
    "exclusionaryFlag": false
  },
  {
    "tierKey": "ev_hybrid",
    "name": "EV / Hybrid Specific",
    "exclusionaryFlag": false
  },
  {
    "tierKey": "exclusionary",
    "name": "Exclusionary (Bumper-to-Bumper)",
    "exclusionaryFlag": true
  },
  {
    "tierKey": "gap",
    "name": "GAP / Add-on",
    "exclusionaryFlag": false
  },
  {
    "tierKey": "high_tech",
    "name": "High-Tech / Electrical",
    "exclusionaryFlag": false
  },
  {
    "tierKey": "maintenance",
    "name": "Maintenance Bundle",
    "exclusionaryFlag": false
  },
  {
    "tierKey": "powertrain",
    "name": "Powertrain",
    "exclusionaryFlag": false
  },
  {
    "tierKey": "powertrain_plus",
    "name": "Powertrain Plus",
    "exclusionaryFlag": false
  },
  {
    "tierKey": "stated_component",
    "name": "Stated Component",
    "exclusionaryFlag": false
  },
  {
    "tierKey": "tire_wheel",
    "name": "Tire & Wheel",
    "exclusionaryFlag": false
  },
  {
    "tierKey": "wrap",
    "name": "Wrap",
    "exclusionaryFlag": false
  }
];

export const MILEAGE_BANDS: BandRow[] = [
  {
    "bandKey": "0_12000",
    "minValue": 0,
    "maxValue": 12000,
    "riskScore": 10,
    "priceMult": 0.85
  },
  {
    "bandKey": "12001_36000",
    "minValue": 12001,
    "maxValue": 36000,
    "riskScore": 20,
    "priceMult": 0.95
  },
  {
    "bandKey": "36001_60000",
    "minValue": 36001,
    "maxValue": 60000,
    "riskScore": 35,
    "priceMult": 1.05
  },
  {
    "bandKey": "60001_85000",
    "minValue": 60001,
    "maxValue": 85000,
    "riskScore": 50,
    "priceMult": 1.2
  },
  {
    "bandKey": "85001_100000",
    "minValue": 85001,
    "maxValue": 100000,
    "riskScore": 65,
    "priceMult": 1.35
  },
  {
    "bandKey": "100001_125000",
    "minValue": 100001,
    "maxValue": 125000,
    "riskScore": 78,
    "priceMult": 1.55
  },
  {
    "bandKey": "125001_150000",
    "minValue": 125001,
    "maxValue": 150000,
    "riskScore": 88,
    "priceMult": 1.75
  },
  {
    "bandKey": "150001_plus",
    "minValue": 150001,
    "maxValue": null,
    "riskScore": 95,
    "priceMult": 1.95
  }
];

export const AGE_BANDS: BandRow[] = [
  {
    "bandKey": "0_3",
    "minValue": 0,
    "maxValue": 3,
    "riskScore": 15,
    "priceMult": 0.95
  },
  {
    "bandKey": "4_6",
    "minValue": 4,
    "maxValue": 6,
    "riskScore": 35,
    "priceMult": 1.05
  },
  {
    "bandKey": "7_10",
    "minValue": 7,
    "maxValue": 10,
    "riskScore": 55,
    "priceMult": 1.2
  },
  {
    "bandKey": "11_15",
    "minValue": 11,
    "maxValue": 15,
    "riskScore": 75,
    "priceMult": 1.35
  },
  {
    "bandKey": "15_plus",
    "minValue": 15,
    "maxValue": null,
    "riskScore": 90,
    "priceMult": 1.5
  }
];

export const OBSERVATIONS: ObservationRow[] = [
  {
    "obsId": 1,
    "vehicleId": 1,
    "vehicleClass": null,
    "coverageTier": "powertrain",
    "termMonths": 36,
    "retailPrice": 1450,
    "sourceType": "estimated"
  },
  {
    "obsId": 2,
    "vehicleId": 1,
    "vehicleClass": null,
    "coverageTier": "exclusionary",
    "termMonths": 60,
    "retailPrice": 3200,
    "sourceType": "estimated"
  },
  {
    "obsId": 3,
    "vehicleId": 2,
    "vehicleClass": null,
    "coverageTier": "stated_component",
    "termMonths": 48,
    "retailPrice": 2400,
    "sourceType": "estimated"
  },
  {
    "obsId": 4,
    "vehicleId": 2,
    "vehicleClass": null,
    "coverageTier": "exclusionary",
    "termMonths": 36,
    "retailPrice": 1800,
    "sourceType": "public_quote"
  },
  {
    "obsId": 5,
    "vehicleId": 6,
    "vehicleClass": null,
    "coverageTier": "exclusionary",
    "termMonths": 48,
    "retailPrice": 2300,
    "sourceType": "public_quote"
  },
  {
    "obsId": 6,
    "vehicleId": 5,
    "vehicleClass": null,
    "coverageTier": "powertrain_plus",
    "termMonths": 36,
    "retailPrice": 1700,
    "sourceType": "estimated"
  },
  {
    "obsId": 7,
    "vehicleId": 3,
    "vehicleClass": null,
    "coverageTier": "exclusionary",
    "termMonths": 48,
    "retailPrice": 3400,
    "sourceType": "estimated"
  },
  {
    "obsId": 8,
    "vehicleId": 4,
    "vehicleClass": null,
    "coverageTier": "comprehensive",
    "termMonths": 48,
    "retailPrice": 3100,
    "sourceType": "estimated"
  },
  {
    "obsId": 9,
    "vehicleId": 7,
    "vehicleClass": null,
    "coverageTier": "exclusionary",
    "termMonths": 48,
    "retailPrice": 4200,
    "sourceType": "estimated"
  },
  {
    "obsId": 10,
    "vehicleId": 7,
    "vehicleClass": null,
    "coverageTier": "powertrain",
    "termMonths": 36,
    "retailPrice": 2200,
    "sourceType": "estimated"
  },
  {
    "obsId": 11,
    "vehicleId": 8,
    "vehicleClass": null,
    "coverageTier": "comprehensive",
    "termMonths": 48,
    "retailPrice": 3300,
    "sourceType": "estimated"
  },
  {
    "obsId": 12,
    "vehicleId": 9,
    "vehicleClass": null,
    "coverageTier": "exclusionary",
    "termMonths": 48,
    "retailPrice": 4800,
    "sourceType": "dealer_quote"
  },
  {
    "obsId": 13,
    "vehicleId": 9,
    "vehicleClass": null,
    "coverageTier": "exclusionary",
    "termMonths": 48,
    "retailPrice": 3900,
    "sourceType": "estimated"
  },
  {
    "obsId": 14,
    "vehicleId": 10,
    "vehicleClass": null,
    "coverageTier": "exclusionary",
    "termMonths": 48,
    "retailPrice": 4300,
    "sourceType": "estimated"
  },
  {
    "obsId": 15,
    "vehicleId": 11,
    "vehicleClass": null,
    "coverageTier": "exclusionary",
    "termMonths": 36,
    "retailPrice": 16238,
    "sourceType": "public_quote"
  },
  {
    "obsId": 16,
    "vehicleId": 11,
    "vehicleClass": null,
    "coverageTier": "ev_hybrid",
    "termMonths": 24,
    "retailPrice": 2400,
    "sourceType": "public_quote"
  },
  {
    "obsId": 17,
    "vehicleId": 12,
    "vehicleClass": null,
    "coverageTier": "powertrain_plus",
    "termMonths": 48,
    "retailPrice": 2100,
    "sourceType": "estimated"
  },
  {
    "obsId": 18,
    "vehicleId": 13,
    "vehicleClass": null,
    "coverageTier": "comprehensive",
    "termMonths": 48,
    "retailPrice": 2700,
    "sourceType": "estimated"
  },
  {
    "obsId": 19,
    "vehicleId": 14,
    "vehicleClass": null,
    "coverageTier": "stated_component",
    "termMonths": 48,
    "retailPrice": 2500,
    "sourceType": "estimated"
  },
  {
    "obsId": 20,
    "vehicleId": 15,
    "vehicleClass": null,
    "coverageTier": "comprehensive",
    "termMonths": 48,
    "retailPrice": 2600,
    "sourceType": "estimated"
  },
  {
    "obsId": 21,
    "vehicleId": 9,
    "vehicleClass": null,
    "coverageTier": "exclusionary",
    "termMonths": 48,
    "retailPrice": 3300,
    "sourceType": "estimated"
  },
  {
    "obsId": 22,
    "vehicleId": 1,
    "vehicleClass": null,
    "coverageTier": "powertrain",
    "termMonths": 36,
    "retailPrice": 1150,
    "sourceType": "estimated"
  },
  {
    "obsId": 23,
    "vehicleId": 1,
    "vehicleClass": null,
    "coverageTier": "powertrain",
    "termMonths": 36,
    "retailPrice": 1900,
    "sourceType": "estimated"
  },
  {
    "obsId": 24,
    "vehicleId": 7,
    "vehicleClass": null,
    "coverageTier": "stated_component",
    "termMonths": 36,
    "retailPrice": 3600,
    "sourceType": "estimated"
  },
  {
    "obsId": 25,
    "vehicleId": null,
    "vehicleClass": "ev",
    "coverageTier": "exclusionary",
    "termMonths": 48,
    "retailPrice": 7550,
    "sourceType": "public_quote"
  },
  {
    "obsId": 26,
    "vehicleId": null,
    "vehicleClass": "ev",
    "coverageTier": "exclusionary",
    "termMonths": 48,
    "retailPrice": 8112,
    "sourceType": "public_quote"
  },
  {
    "obsId": 27,
    "vehicleId": 5,
    "vehicleClass": null,
    "coverageTier": "exclusionary",
    "termMonths": 60,
    "retailPrice": 2900,
    "sourceType": "estimated"
  },
  {
    "obsId": 28,
    "vehicleId": 3,
    "vehicleClass": null,
    "coverageTier": "powertrain",
    "termMonths": 36,
    "retailPrice": 2000,
    "sourceType": "estimated"
  },
  {
    "obsId": 29,
    "vehicleId": 10,
    "vehicleClass": null,
    "coverageTier": "exclusionary",
    "termMonths": 48,
    "retailPrice": 6200,
    "sourceType": "dealer_quote"
  },
  {
    "obsId": 30,
    "vehicleId": 6,
    "vehicleClass": null,
    "coverageTier": "powertrain_plus",
    "termMonths": 48,
    "retailPrice": 2200,
    "sourceType": "estimated"
  },
  {
    "obsId": 31,
    "vehicleId": 12,
    "vehicleClass": null,
    "coverageTier": "powertrain",
    "termMonths": 36,
    "retailPrice": 1500,
    "sourceType": "estimated"
  },
  {
    "obsId": 32,
    "vehicleId": 7,
    "vehicleClass": null,
    "coverageTier": "powertrain",
    "termMonths": 36,
    "retailPrice": 2000,
    "sourceType": "estimated"
  }
];
