#!/usr/bin/env python3
"""Generate the TypeScript engine's data + cross-language parity fixtures.

Python is the single source of truth. This script:
  1. emits packages/warranty-engine/src/data.generated.ts (typed `as const` data), and
  2. emits packages/warranty-engine/test/fixtures.generated.json — canonical input->output
     cases computed by the PYTHON engine, which the TS test suite must reproduce.

Run after changing seed data or engine constants:
    python scripts/export_ts_data.py
"""
from __future__ import annotations

import datetime as _dt
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "src"))

from drivewayadvocate import db as dbm          # noqa: E402
from drivewayadvocate import pricing, scoring     # noqa: E402

PKG = REPO_ROOT / "packages" / "warranty-engine"
DATA_TS = PKG / "src" / "data.generated.ts"
FIXTURES_JSON = PKG / "test" / "fixtures.generated.json"

SNAKE_TO_CAMEL = {
    "brand_repair_cost": "brandRepairCost",
    "model_reliability": "modelReliability",
    "powertrain_complexity": "powertrainComplexity",
    "electronics_complexity": "electronicsComplexity",
    "known_failure_points": "knownFailurePoints",
    "luxury_parts_cost": "luxuryPartsCost",
    "hybrid_ev_components": "hybridEvComponents",
    "claims_likelihood": "claimsLikelihood",
}


def _b(v) -> bool:
    return bool(v)


def build_data(conn):
    vehicles = [
        {
            "vehicleId": r["vehicle_id"], "year": r["year"], "make": r["make"],
            "model": r["model"], "trim": r["trim"], "vehicleClass": r["vehicle_class"],
            "segment": r["segment"], "luxuryFlag": _b(r["luxury_flag"]),
            "powertrain": r["powertrain"], "turboFlag": _b(r["turbo_flag"]),
            "drivetrain": r["drivetrain"],
        }
        for r in conn.execute("SELECT * FROM vehicles ORDER BY vehicle_id")
    ]
    risk = [
        {
            "vehicleId": r["vehicle_id"],
            "brandRepairCost": r["brand_repair_cost"],
            "modelReliability": r["model_reliability"],
            "powertrainComplexity": r["powertrain_complexity"],
            "electronicsComplexity": r["electronics_complexity"],
            "knownFailurePoints": r["known_failure_points"],
            "luxuryPartsCost": r["luxury_parts_cost"],
            "hybridEvComponents": r["hybrid_ev_components"],
            "claimsLikelihood": r["claims_likelihood"],
            "referenceTotal": r["reference_total"],
        }
        for r in conn.execute("SELECT * FROM vehicle_risk_scores ORDER BY vehicle_id")
    ]
    tiers = [
        {"tierKey": r["tier_key"], "name": r["name"], "exclusionaryFlag": _b(r["exclusionary_flag"])}
        for r in conn.execute("SELECT * FROM coverage_tiers ORDER BY tier_key")
    ]
    mileage_bands = [
        {"bandKey": r["band_key"], "minValue": r["min_miles"], "maxValue": r["max_miles"],
         "riskScore": r["risk_score"], "priceMult": r["price_mult"]}
        for r in conn.execute("SELECT * FROM mileage_bands ORDER BY min_miles")
    ]
    age_bands = [
        {"bandKey": r["band_key"], "minValue": r["min_years"], "maxValue": r["max_years"],
         "riskScore": r["risk_score"], "priceMult": r["price_mult"]}
        for r in conn.execute("SELECT * FROM age_bands ORDER BY min_years")
    ]
    observations = [
        {
            "obsId": r["obs_id"], "vehicleId": r["vehicle_id"],
            "vehicleClass": r["vehicle_class"], "coverageTier": r["coverage_tier"],
            "termMonths": r["term_months"], "retailPrice": r["retail_price"],
            "sourceType": r["source_type"],
        }
        for r in conn.execute("SELECT * FROM pricing_observations ORDER BY obs_id")
    ]
    return vehicles, risk, tiers, mileage_bands, age_bands, observations


_HEADER = """// AUTO-GENERATED by scripts/export_ts_data.py — DO NOT EDIT BY HAND.
// Source of truth: database/seed/*.csv (regenerate with: python scripts/export_ts_data.py)

export interface VehicleRow {
  vehicleId: number; year: number; make: string; model: string; trim: string | null;
  vehicleClass: string; segment: string; luxuryFlag: boolean; powertrain: string;
  turboFlag: boolean; drivetrain: string;
}
export interface RiskScoreRow {
  vehicleId: number; brandRepairCost: number; modelReliability: number;
  powertrainComplexity: number; electronicsComplexity: number; knownFailurePoints: number;
  luxuryPartsCost: number; hybridEvComponents: number; claimsLikelihood: number;
  referenceTotal: number;
}
export interface CoverageTierRow { tierKey: string; name: string; exclusionaryFlag: boolean; }
export interface BandRow {
  bandKey: string; minValue: number; maxValue: number | null; riskScore: number; priceMult: number;
}
export interface ObservationRow {
  obsId: number; vehicleId: number | null; vehicleClass: string | null; coverageTier: string;
  termMonths: number | null; retailPrice: number | null; sourceType: string;
}
"""


def _emit_const(name: str, typ: str, rows: list) -> str:
    return f"export const {name}: {typ} = {json.dumps(rows, indent=2)};\n"


def write_data_ts(vehicles, risk, tiers, mileage_bands, age_bands, observations) -> None:
    parts = [_HEADER]
    parts.append(f'export const DATA_VERSION = "0.1.0";\n')
    parts.append(f'export const DATA_GENERATED_AT = "{_dt.date.today().isoformat()}";\n\n')
    parts.append(_emit_const("VEHICLES", "VehicleRow[]", vehicles))
    parts.append(_emit_const("RISK_SCORES", "RiskScoreRow[]", risk))
    parts.append(_emit_const("COVERAGE_TIERS", "CoverageTierRow[]", tiers))
    parts.append(_emit_const("MILEAGE_BANDS", "BandRow[]", mileage_bands))
    parts.append(_emit_const("AGE_BANDS", "BandRow[]", age_bands))
    parts.append(_emit_const("OBSERVATIONS", "ObservationRow[]", observations))
    DATA_TS.parent.mkdir(parents=True, exist_ok=True)
    DATA_TS.write_text("\n".join(parts), encoding="utf-8")


# --- Parity fixtures ----------------------------------------------------------
SCORE_CASES = [
    ("Toyota", "Camry", 36000, 3, 2021),
    ("Toyota", "Camry", 30000, 5, 2021),
    ("Toyota", "Camry", 120000, 9, 2021),
    ("Honda", "Accord", 45000, 5, 2021),
    ("Honda", "CR-V", 48000, 5, 2021),
    ("Ford", "F-150", 55000, 5, 2021),
    ("Chevrolet", "Silverado 1500", 55000, 5, 2021),
    ("Toyota", "RAV4", 45000, 5, 2021),
    ("Jeep", "Grand Cherokee", 55000, 5, 2021),
    ("Dodge", "Charger", 55000, 5, 2021),
    ("BMW", "3 Series", 45000, 5, 2021),
    ("Mercedes-Benz", "C-Class", 55000, 5, 2021),
    ("Tesla", "Model 3", 40000, 5, 2021),
    ("Hyundai", "Elantra", 45000, 5, 2021),
    ("Kia", "Telluride", 55000, 5, 2021),
    ("Nissan", "Altima", 55000, 5, 2021),
    ("Subaru", "Outback", 55000, 5, 2021),
    # reference conditions: must equal reference_total
    ("BMW", "3 Series", 36000, 3, 2021),
    ("Jeep", "Grand Cherokee", 36000, 3, 2021),
]

# Unknown-vehicle fallback cases (attribute heuristic).
SCORE_FALLBACK_CASES = [
    {"make": "Porsche", "model": "911", "miles": 20000, "years": 2,
     "attrs": {"segment": "luxury", "luxury": True, "turbo": True, "drivetrain": "awd"}},
    {"make": "Toyota", "model": "Corolla", "miles": 40000, "years": 4, "attrs": {"segment": "economy"}},
    {"make": "Rivian", "model": "R1T", "miles": 15000, "years": 2,
     "attrs": {"segment": "luxury", "luxury": True, "powertrain": "ev", "drivetrain": "awd"}},
]

PRICE_CASES = [
    dict(make="BMW", model="3 Series", year=2021, mileage=45000, term_months=36, tier="exclusionary", dealer_offer=4200),
    dict(make="Toyota", model="Camry", year=2021, mileage=45000, term_months=36, tier="exclusionary", dealer_offer=4200),
    dict(make="Toyota", model="Camry", year=2021, mileage=30000, term_months=36, tier="powertrain"),
    dict(make="Toyota", model="Camry", year=2021, mileage=45000, term_months=36, tier="powertrain", dealer_offer=6000),
    dict(make="Honda", model="Accord", year=2021, mileage=45000, term_months=48, tier="stated_component"),
    dict(make="Jeep", model="Grand Cherokee", year=2021, mileage=55000, term_months=48, tier="exclusionary", dealer_offer=4200),
    dict(make="Mercedes-Benz", model="C-Class", year=2021, mileage=55000, term_months=48, tier="exclusionary", dealer_offer=6200),
    dict(make="Tesla", model="Model 3", year=2021, mileage=40000, term_months=36, tier="ev_hybrid"),
    dict(make="Ford", model="F-150", year=2021, mileage=55000, term_months=48, tier="comprehensive", deductible=0),
    dict(make="Subaru", model="Outback", year=2021, mileage=55000, term_months=48, tier="comprehensive"),
    dict(make="Nissan", model="Altima", year=2021, mileage=120000, term_months=36, tier="stated_component"),
    dict(make="Toyota", model="Camry", year=2021, mileage=45000, term_months=36, tier="powertrain", deductible=500),
    dict(make="Toyota", model="Camry", year=2021, mileage=45000, term_months=36, tier="powertrain", deductible=0),
    dict(make="Toyota", model="Camry", year=2021, mileage=45000, term_months=60, tier="exclusionary"),
    dict(make="Toyota", model="Camry", year=2021, mileage=45000, term_months=24, tier="exclusionary"),
    dict(make="Toyota", model="Corolla", year=2021, mileage=45000, term_months=36, tier="stated_component"),
    dict(make="Toyota", model="Corolla", year=2021, mileage=45000, term_months=36, tier="made_up_tier"),
    dict(make="Honda", model="CR-V", year=2021, mileage=55000, term_months=48, tier="powertrain_plus", current_warranty_active=True),
    dict(make="Porsche", model="911", year=2022, mileage=20000, term_months=48, tier="exclusionary",
         segment="luxury", luxury=True, turbo=True, drivetrain="awd"),
]

CAMEL = {
    "make": "make", "model": "model", "year": "year", "mileage": "mileage",
    "term_months": "termMonths", "tier": "tier", "deductible": "deductible",
    "dealer_offer": "dealerOffer", "current_warranty_active": "currentWarrantyActive",
    "segment": "segment", "luxury": "luxury", "powertrain": "powertrain",
    "turbo": "turbo", "drivetrain": "drivetrain", "trim": "trim",
    "term_mileage": "termMileage", "state": "state",
}


def _camel_input(d: dict) -> dict:
    return {CAMEL[k]: v for k, v in d.items()}


def build_fixtures(conn) -> dict:
    score_cases = []
    for make, model, miles, years, year in SCORE_CASES:
        s = scoring.score_vehicle(make, model, miles, years, conn=conn, year=year)
        score_cases.append({
            "input": {"make": make, "model": model, "miles": miles, "years": years, "year": year},
            "expected": {
                "fullScore": s.full_score, "intrinsicScore": s.intrinsic_score,
                "mileageScore": s.mileage_score, "ageScore": s.age_score,
                "riskLabel": s.risk_label(), "source": s.source,
                "topDrivers": [SNAKE_TO_CAMEL[d] for d in s.top_drivers],
            },
        })
    for c in SCORE_FALLBACK_CASES:
        s = scoring.score_vehicle(c["make"], c["model"], c["miles"], c["years"], conn=conn, **c["attrs"])
        score_cases.append({
            "input": {"make": c["make"], "model": c["model"], "miles": c["miles"],
                      "years": c["years"], "attrs": c["attrs"]},
            "expected": {
                "fullScore": s.full_score, "intrinsicScore": s.intrinsic_score,
                "mileageScore": s.mileage_score, "ageScore": s.age_score,
                "riskLabel": s.risk_label(), "source": s.source,
                "topDrivers": [SNAKE_TO_CAMEL[d] for d in s.top_drivers],
            },
        })

    price_cases = []
    for kw in PRICE_CASES:
        req = pricing.QuoteRequest(**kw)
        r = pricing.price_quote(req, conn)
        price_cases.append({
            "input": _camel_input(kw),
            "expected": {
                "fairLow": r.fair_low, "fairMid": r.fair_mid, "fairHigh": r.fair_high,
                "dealerCostEst": r.dealer_cost_est, "negotiationTarget": r.negotiation_target,
                "perYearFair": r.per_year_fair, "observedN": r.observed_n,
                "verdict": r.verdict, "markupVsCostPct": r.markup_vs_cost_pct,
                "offerVsFairPct": r.offer_vs_fair_pct, "markupWarning": r.markup_warning,
                "recommendation": r.recommendation, "confidence": r.confidence,
                "fullScore": r.score.full_score,
            },
        })

    return {
        "generatedAt": _dt.date.today().isoformat(),
        "scoreCases": score_cases,
        "priceCases": price_cases,
    }


def main() -> int:
    conn = dbm.build_in_memory()
    try:
        data = build_data(conn)
        write_data_ts(*data)
        fixtures = build_fixtures(conn)
    finally:
        conn.close()

    FIXTURES_JSON.parent.mkdir(parents=True, exist_ok=True)
    FIXTURES_JSON.write_text(json.dumps(fixtures, indent=2) + "\n", encoding="utf-8")

    print(f"wrote {DATA_TS.relative_to(REPO_ROOT)}")
    print(f"wrote {FIXTURES_JSON.relative_to(REPO_ROOT)} "
          f"({len(fixtures['scoreCases'])} score + {len(fixtures['priceCases'])} price cases)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
